### ISSUE TITLE
numeric uid owner breaks salt file module/state

### ISSUE THREAD

**Issue by darix** [openSUSE/salt#296]
### Description of Issue

This output is from a state.highstate. the file on the machine is owned by an unresolvable UID. 

```
          ID: zypp_conf_solver_dupAllowVendorChange
    Function: file.replace
        Name: /etc/zypp/zypp.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1987, in call
                  ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2031, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/file.py", line 4823, in replace
                  backslash_literal=backslash_literal)
                File "/usr/lib/python3.6/site-packages/salt/modules/file.py", line 2485, in replace
                  check_perms(path, None, pre_user, pre_group, pre_mode)
                File "/usr/lib/python3.6/site-packages/salt/modules/file.py", line 4577, in check_perms
                  not salt.utils.platform.is_windows() and salt.utils.stringutils.to_str(user) != perms['luser']
                File "/usr/lib/python3.6/site-packages/salt/utils/stringutils.py", line 103, in to_str
                  raise TypeError('expected str, bytes, or bytearray not {}'.format(type(s)))
              TypeError: expected str, bytes, or bytearray not <class 'int'>
     Started: 16:44:07.373835
    Duration: 5.901 ms
     Changes:   
```

you can also reproduce it with

```
salt '*' file.check_perms /etc/zypp/locks '{}' 65433 root 644

hostname:
    Passed invalid arguments to file.check_perms: expected str, bytes, or bytearray not <class 'int'>
```

### Versions Report

```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.36.0
           Mako: 1.1.3
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 3.9.8
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.8.6 (default, Nov 09 2020, 12:09:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: opensuse-tumbleweed 20201121 n/a
         locale: utf-8
        machine: x86_64
        release: 5.8.15-1-default
         system: Linux
        version: openSUSE Tumbleweed 20201121 n/a
```

**Comment by meaksh** [comment]
Thanks for reporting this issue @darix :+1:

**Comment by vzhestkov** [comment]
Closing as fixed
