### ISSUE TITLE
[BUG] running pkg.version_cmp on openEuler minions fails

### ISSUE THREAD

**Issue by raulillo82** [openSUSE/salt#540]
**Description**
Running pkg.version_cmp on openEuler minions fails. PR fixing the problem will be created soon.

**Setup**
Salt master is a uyuni server, latest available version (based on opensuse 15.4). Salt minion is an openEuler 22.03 LTS with latest patches.

- [ ] on-prem machine
- [X] VM (KVM)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1916, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1873, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
        return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/yumpkg.py", line 685, in version_cmp
        return __salt__["lowpkg.version_cmp"](pkg1, pkg2, ignore_epoch=ignore_epoch)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/context.py", line 78, in __getitem__
        return self.value()[item]
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 334, in __getitem__
        super().__getitem__(item)  # try to get the item from the dictionary
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/lazy.py", line 105, in __getitem__
        raise KeyError(key)
    KeyError: 'lowpkg.version_cmp'
ERROR: Minions returned with non-zero exit code

uyuni:~ # salt '192*' grains.get os_family
192.168.122.173:
    openEuler
```

**Expected behavior**
```
uyuni:~ # salt '192*' grains.get os_family
192.168.122.173:
    openEuler

uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    1
```

**Screenshots**

**Versions Report**
Master:
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
uyuni:~ # salt --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.3.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 1.7.0
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: opensuse-leap 15.4 
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150400.22-default
        system: Linux
       version: openSUSE Leap 15.4 
```
</details>

Minion:
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@openeuler ~]# venv-salt-call --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: 4.2.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.10.2 (main, Mar 01 2022, 07:23:53) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.2.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: openeuler 22.03 
        locale: utf-8
       machine: x86_64
       release: 5.10.0-60.18.0.50.oe2203.x86_64
        system: Linux
       version: openEuler 22.03 

```
</details>

**Additional context**

**Comment by brejoc** [comment]
@raulillo82 Hey Raúl, good to see you. I just noticed this PR and was wondering about the title. Would you mind giving it a proper title? "[BUG]" could be a bit confusing. 😉
